global using System.Numerics;
global using Fibonacci.DomainModel.Calculation;
global using Fibonacci.DomainModel.Calculation.Logic;
global using Fibonacci.DomainModel.Calculation.Logic.Service;
global using Fibonacci.DomainModel.Calculation.Result.Publishers;
global using Fibonacci.DomainUseCases.Calculation;
global using Fibonacci.DomainUseCases.Calculation.Actions.SendResult;
global using Fibonacci.DomainUseCases.Calculation.DTOs;
global using Moq;
